// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALclZlctjGG06narjbWRGD_TekddShmkg',
    appId: '1:995621612411:web:9ccac6083036cd07dd2bde',
    messagingSenderId: '995621612411',
    projectId: 'servicio-social2025',
    authDomain: 'servicio-social2025.firebaseapp.com',
    storageBucket: 'servicio-social2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD18CJswHLZbkVVNIaZPengUteDqST4l3U',
    appId: '1:995621612411:android:5e89f6045a19c2addd2bde',
    messagingSenderId: '995621612411',
    projectId: 'servicio-social2025',
    storageBucket: 'servicio-social2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB2YysiRgKtxZKASd4PmbV30v9gJh-Xt4',
    appId: '1:995621612411:ios:bfbc3f014cf34b6cdd2bde',
    messagingSenderId: '995621612411',
    projectId: 'servicio-social2025',
    storageBucket: 'servicio-social2025.firebasestorage.app',
    iosBundleId: 'com.example.ss2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB2YysiRgKtxZKASd4PmbV30v9gJh-Xt4',
    appId: '1:995621612411:ios:bfbc3f014cf34b6cdd2bde',
    messagingSenderId: '995621612411',
    projectId: 'servicio-social2025',
    storageBucket: 'servicio-social2025.firebasestorage.app',
    iosBundleId: 'com.example.ss2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALclZlctjGG06narjbWRGD_TekddShmkg',
    appId: '1:995621612411:web:68f393296ebbdfb7dd2bde',
    messagingSenderId: '995621612411',
    projectId: 'servicio-social2025',
    authDomain: 'servicio-social2025.firebaseapp.com',
    storageBucket: 'servicio-social2025.firebasestorage.app',
  );
}
